database:
  mysql:
    host: 127.0.0.1
    port: "3306"
    user: root
    password: "123456"
    db_name: library_sys_go
    charset: utf8mb4
  redis:
    host: 127.0.0.1
    port: "6379"
    password: ""
    db: 2
