name: 最新版

on: [push, pull_request]

jobs:
  doc:
    name: Update doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: "1.20"
      - name: Setup swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
      - name: Update doc
        run: |
          cd hack
          bash doc.sh
      - name: Check has change
        id: check
        run: |
          git diff --exit-code
          echo "::set-output name=has_change::false"
          if [ $? -eq 1 ]; then
            echo "::set-output name=has_change::true"
          fi
      - name: Commit files
        if: steps.check.outputs.has_change == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "doc: 更新文档"
      - name: Push to github
        if: steps.check.outputs.has_change == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    needs: doc
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
      fail-fast: true
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: "1.20"
      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd hack
          bash releaser.sh
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: library_sys_go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          path: hack/out
