name: 发行版

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build And Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: true

    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: "1.20"
      - name: Build binary file
        run: |
          cd hack
          bash releaser.sh
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: library_sys_go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          path: hack/out/*.tar.gz

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: ~/download/artifact
      - name: Prepare Files
        run: |
          cd ~/download/artifact
          mv library_sys_go-*/* ~/artifact
          rm -rf library_sys_go-*
          ls ~/artifact
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ~/artifact/*
          draft: true
